language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-dropwizard' ]; then cd .. && eval "mv $currentfolder generator-dropwizard" && cd generator-dropwizard; fi

